# Generated by Django 3.1.7 on 2021-04-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210401_2019'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follows',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_follows'),
        ),
    ]
